spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3309/gaya_dev
    username: gaya_dev_user
    password: gaya
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
