spring:
  datasource:
    url: jdbc:mysql://localhost:3309/gaya_dev
    username: gaya_dev_user
    password: gaya
  jpa:
    hibernate:
      ddl-auto: validate
    #database-platform: "org.hibernate.dialect.MySQL5Dialect"
    database: mysql
    show-sql: true
    properties:
          jakarta:
            persistence:
              schema-generation:
                create-source: metadata
                scripts:
                  action: create
                  create-target: create.sql